### ISSUE TITLE
Totals row should have Totals in the file name column

### ISSUE THREAD

**Issue by pacmaninbw** [pacmaninbw/StaticCodeEvalTools#16]

**Comment by tms13** [comment]
[POSIX spec for `wc`](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/wc.html#tag_20_154_10) says:
> If more than one input file operand is specified, an additional line shall be written, of the same format as the other lines, except that the word **total** (in the POSIX locale) shall be written instead of a pathname and the total of each column shall be written as appropriate. Such an additional line, if any, is written at the end of the output.

**Comment by pacmaninbw** [comment]
This has been fixed in the most recent version of the source, the totals line will now contain "Totals" in the file name column.
