### ISSUE TITLE
Implement a single CMake version rather than SLN file and separate Make

### ISSUE THREAD

**Issue by beroset** [pacmaninbw/StaticCodeEvalTools#4]
Right now, the `.sln` file and `Makefile` are completely separate and represent double the maintenance effort to keep synchronized.  Better would be to implement both as a single CMake project which would allow creating either version from the same sources.

**Comment by pacmaninbw** [comment]
I agree for the future, I need to make changes to my current development environment first.

**Comment by pacmaninbw** [comment]
Edward. feel free to contribute a CMake file.

**Comment by beroset** [comment]
Addressed via merged PR.

**Comment by pacmaninbw** [comment]
Edward, I think I got the modifications correct in the CMakeLists.txt file now.
